# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest #Changed from ubuntu to Windows as it needs VS support
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    vsVersion: '16.0'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

steps:
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'